// JsFromRoutes CacheKey 915329f9e8ef4ae431d7f2535be69f6c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/exercises'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/v1/exercises'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/v1/exercises/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/v1/exercises/:id'),
}
