// JsFromRoutes CacheKey 4ce5b3c5d4d28cc1cedefafbb3533355
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/exercises'),
}
