// JsFromRoutes CacheKey f2de6e73378759ef989bb6edda6e7477
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/api/v1/meals/:meal_id/food_entries'),
  rescale: /* #__PURE__ */ definePathHelper('post', '/api/v1/food_entries/:id/rescale'),
  estimate: /* #__PURE__ */ definePathHelper('post', '/api/v1/food_entries/:id/estimate'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/v1/food_entries/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/v1/food_entries/:id'),
}
