// JsFromRoutes CacheKey 1525f036892516398dc963c03615d434
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/api/v1/health'),
}
