// JsFromRoutes CacheKey b68a9043430e318fcbc16cd12b149ab3
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  parse: /* #__PURE__ */ definePathHelper('post', '/api/v1/meals/:id/parse'),
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/meals'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/v1/meals'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/v1/meals/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/v1/meals/:id'),
}
