// JsFromRoutes CacheKey b16e5d5fe4170e627f198610f3dd30fc
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/progressions'),
}
