// JsFromRoutes CacheKey 4a65a16e3299aff84538e28635b3ad1d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/programs'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/v1/programs'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/v1/programs/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/v1/programs/:id'),
}
