// JsFromRoutes CacheKey d6a71d9c7a40b2edd2d2926aee79614f
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/routines'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/v1/routines'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/v1/routines/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/v1/routines/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/v1/routines/:id'),
}
