// JsFromRoutes CacheKey 15bd97a4898cdc90b9d789c93e6712a2
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/routines'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/v1/routines/:id'),
}
