// JsFromRoutes CacheKey 3052ca6e81028d90103c79646af78bd7
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/api/v1/session'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/v1/session'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/v1/session'),
}
