// JsFromRoutes CacheKey 1b2613d36b82fcd2361a3299ea4a9996
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  create: /* #__PURE__ */ definePathHelper('post', '/api/v1/workouts/:workout_id/set_logs'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/v1/set_logs/:id'),
}
