// JsFromRoutes CacheKey 52d3c2c7129e35b5912034a09b858f11
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/users'),
}
