// JsFromRoutes CacheKey 4728ddfb6ff2acfefd4c9ab2cccf6593
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  current: /* #__PURE__ */ definePathHelper('get', '/api/v1/workouts/current'),
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/workouts'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/v1/workouts'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/v1/workouts/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/v1/workouts/:id'),
}
