// JsFromRoutes CacheKey 9fe1ab7e5a9165bce6b3cbcbbf115820
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  current: /* #__PURE__ */ definePathHelper('get', '/api/v1/workouts/current'),
  index: /* #__PURE__ */ definePathHelper('get', '/api/v1/workouts'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/v1/workouts'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/v1/workouts/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/v1/workouts/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/v1/workouts/:id'),
}
